#!/bin/sh
# Preprocess IStatusBar and KeyguardService stuff since they vary between versions
# (e.g Android 16 vs Android 16 QPR2 have different versions of those)

cd "$(dirname "$0")" || exit 1

. ./target.sh

CPP_ARGS=""

if [ -n "$IS_BAKLAVA_QPR1_LATER" ]; then
  CPP_ARGS="$CPP_ARGS -DBAKLAVA_QPR1_LATER"
fi
if [ -n "$IS_BAKLAVA_QPR2_LATER" ]; then
  CPP_ARGS="$CPP_ARGS -DBAKLAVA_QPR2_LATER"
fi

toPreprocess() {
  # shellcheck disable=SC2086
  cpp $CPP_ARGS -P -o "main/java/eu/hn1f/holoui/$1.pre" "preprocess/$1" || return 1
  printf "// THIS FILE IS AUTOGENERATED by preprocessStuff.sh
// MODIFY THE FILE AT \"app/src/preprocess/%s\" INSTEAD\n\n" "$1" > "main/java/eu/hn1f/holoui/$1"
  cat "main/java/eu/hn1f/holoui/$1.pre" >> "main/java/eu/hn1f/holoui/$1"
  rm "main/java/eu/hn1f/holoui/$1.pre"
}

toPreprocess KeyguardService.kt || exit 1
toPreprocess StatusBarImpl.kt || exit 1